version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: daily
      time: "12:45"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "dependabot"
