name: Cypress Test Execution

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:  
    - uses: actions/checkout@v3
    - name: Use Node.js 18
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - uses: isbang/compose-action@v1.5.1
      with:
        compose-file: "${{ github.workspace }}/docker-compose.yml"
        down-flags: "--volumes" 
        
    - name: Cypress Run
      working-directory: ./cypress
      run: |
        npm install
        npm run test
